#!/usr/bin/env node

const Module = require("module");

const exampleName = process.argv[2];

if (!exampleName) {
  // eslint-disable-next-line no-console
  console.error("Example missing");
  process.exit(1);
}

// Substitute with local version
Module._load = new Proxy(Module._load, {
  apply(target, context, args) {
    if (args[0] === "express-inspector") {
      args[0] = require.resolve("..");
    }
    return Reflect.apply(target, context, args);
  }
});

require(`./${exampleName}`);
